# Generated by Django 4.2.13 on 2024-05-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Модель №1')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoesModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='photoes')),
                ('model1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vagnertest.model1')),
            ],
        ),
    ]
