# Generated by Django 4.2.13 on 2024-05-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagnertest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoesmodel1',
            name='model1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photoes', to='vagnertest.model1'),
        ),
    ]
