# Generated by Django 4.2.13 on 2024-05-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagnertest', '0002_photoessmall_photoesbig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoesbig',
            old_name='imgage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='photoessmall',
            old_name='imgage',
            new_name='image',
        ),
    ]
